### ISSUE TITLE
Show objectives not assigned to a group in the breakdown

### ISSUE THREAD

**Issue by amdw** [google/peoplemath#165]
Right now, the "assignments by (group type)" breakdown in the period view doesn't include objectives that aren't assigned to a group of that type.

It would be good to see those under a heading like "no (group type)", as this would make it easier to identify ungrouped objectives and assign those to a group if desired.

**Comment by r-sreesaran** [comment]
I could work on this.

**Comment by amdw** [comment]
Hi @r-sreesaran - thanks ever so much for the offer!

I need this feature pretty soon for work purposes, so am likely to start working on it myself shortly.

If you are able to send me a PR before I'm able to complete one myself, great, but I'm likely to have one ready within the next few hours.

**Comment by r-sreesaran** [comment]
Please proceed. I will work some other issue.
