### ISSUE TITLE
Show cumulative sum of estimates within bucket

### ISSUE THREAD

**Issue by amdw** [google/peoplemath#17]
It would be useful to see the cumulative sum of the effort estimates for each objective, in descending priority order within each bucket.

This would give a sense of which objectives it's likely to be possible to work on during the period, based on the resource limits for each bucket, without actually assigning the objectives.

The numbers could be shown on the right of each bucket, perhaps colour coded to show when the cumulative sum rises above the resource limit.

**Comment by r-sreesaran** [comment]
I would like to pick this up.

**Comment by amdw** [comment]
@r-sreesaran - many thanks!

The one warning I'd give is that it might be a bit fiddly to get this just right in the UI.

For example, we have to consider what happens if an objective is long enough that it needs to be wrapped, or what happens if the screen is shrunk horizontally. We need to make sure nothing nasty happens, like the objective text overlapping the new UI element.

I'd love to see your ideas, though, if you've got time to have a go!

**Comment by r-sreesaran** [comment]
"It would be useful to see the cumulative sum of the effort estimates for each objective, in descending priority order within each bucket."
From your initial statement I could understand cumulative sum and objective name needs to be displayed separately from the existing objective?.  like in a separate  component within the bucket. 

Is my understanding correct ?.

**Comment by r-sreesaran** [comment]
just to get a understanding on location of the cumulative sum. I have uploaded a wireframe. 
![proposals](https://user-images.githubusercontent.com/3852618/101040041-06345880-35a2-11eb-8b7a-e1deb6537656.jpg)

**Comment by amdw** [comment]
@r-sreesaran - thanks for the picture!

I did a very rough mock-up of what I had in mind [here](https://docs.google.com/drawings/d/1EONGFDm9gSDFxjTIawx3BuI7d-8Wn5OHtL6_WSZJ1pU/edit?usp=sharing).

I was thinking that the cumulative sums would appear aligned with each other on the right-hand side. This would make it nice and easy for the eye to scan downwards along the column of numbers.

* They'd start off in some neutral colour like grey, for objectives that can be completely accommodated within the current bucket resource limit (99 person weeks in this case).
* Then, if there's an objective that partially straddles the resource limit, that one would be a warning colour like orange, to indicate that this objective can only be partially accommodated if we allocate in strict descending priority order.
* Then, below that, the colour would become a stronger warning colour, like light red, to show that these objectives can't be accommodated at all within the current limit.

The objectives in this mock-up are nice and short, but we'd need to consider what happens if the objective wording is long enough that it needs to be wrapped. Obviously in this case it shouldn't overlap the cumulative sum; the wrapping should happen based on the width of the row *minus* the cumulative sum, and the sum should remain vertically aligned in the middle of the row.

That's what I was thinking, but I'm open to counter-proposals.

Many thanks!

**Comment by amdw** [comment]
Thank you @r-sreesaran for your work on this issue!

**Comment by r-sreesaran** [comment]
@amdw Thanks for all the code reviews.
