### ISSUE TITLE
Make HTTP errors more noticeable

### ISSUE THREAD

**Issue by amdw** [google/peoplemath#39]
A couple of times I've accidentally dismissed the snackbar that tells you a concurrent edit has been made.

This error should be made more noticeable - perhaps a modal that can only be dismissed by clicking a certain button, and/or maybe pressing the escape key?

It should prompt the user to copy any unsaved work and then reload the page.

**Comment by amdw** [comment]
This is probably an issue with all errors, not just concurrent modification errors.

**Comment by amdw** [comment]
This should now be much easier to resolve using the new `NotificationService` introduced by @Samrthi.

**Comment by r-sreesaran** [comment]
I would like to work on this issue.

**Comment by amdw** [comment]
@r-sreesaran - great, thanks very much!

All these errors should go through the `NotificationService`, so that we can decide centrally there how to display them. Off the top of my head I'm not sure how consistently we're already doing that.
