### ISSUE TITLE
Add Gorilla Web Toolkit

### ISSUE THREAD

**Issue by vavilen84** [google/peoplemath#45]
Docs https://www.gorillatoolkit.org/ .

This is flexible tool, this will allow us to create a separate route for each method (GET, POST) so we dont need to use if/else condition.

@amdw reply
Sounds good - the Gorilla libraries seem quite well-regarded, so if this simplifies the code then I'm all for it!

**Comment by amdw** [comment]
I believe this was resolved by #49 - thank you! Please reopen if I misunderstood.
